project_id = "mvjfepuvxgzgmgawubfx"

[functions.workshop-finder]
verify_jwt = false

[functions.concierge]
verify_jwt = false

[functions.send-recommendations]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.adhdi-ask]
verify_jwt = false
