import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageCTA from "@/components/templates/PageCTA";
import PullQuote from "@/components/blocks/PullQuote";
import KeyIssuesGrid from "@/components/blocks/KeyIssuesGrid";
import WhatIsBreaking from "@/components/blocks/WhatIsBreaking";
import PositivesBlock from "@/components/blocks/PositivesBlock";
import OutcomeBlock from "@/components/blocks/OutcomeBlock";
import RelevantWorkshops from "@/components/blocks/RelevantWorkshops";
import TestimonialBlock from "@/components/blocks/TestimonialBlock";
import AccessibilityNote from "@/components/blocks/AccessibilityNote";
import Breadcrumbs from "@/components/Breadcrumbs";
import SEOHead from "@/components/SEOHead";
import JsonLd, { breadcrumbSchema, serviceSchema, faqSchema } from "@/components/JsonLd";
import { Train, Monitor, Moon, Users, ShieldAlert } from "lucide-react";
import { NEURO_COLOURS } from "@/data/neuroColours";
import ndRailImg from "@/assets/blog/neurodiversity-rail.jpg";

const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: (i: number) => ({ opacity: 1, y: 0, transition: { delay: i * 0.1, duration: 0.5, ease: "easeOut" as const } }) };
const faqs = [
  { question: "How do you deliver training across a dispersed operational workforce?", answer: "We deliver in flexible formats including on-site depot sessions, digital modules, and manager briefings designed to cascade to operational teams." },
  { question: "How does neurodiversity interact with our safety management system?", answer: "We work with safety and HR teams to map neurodiversity onto existing frameworks, including fatigue risk management and non-technical skills assessments." },
  { question: "Our driver managers need to handle disclosure conversations. Can you train them?", answer: "Yes. We train managers to handle disclosure in safety-critical contexts, separate fitness-for-role concerns from adjustment conversations." },
  { question: "We have a heritage rail operation. Does your training work at smaller scale?", answer: "Yes. We adapt delivery to organisation size and volunteer-staff mix." },
];
const keyIssues = [
  { title: "Control room cognitive demand", description: "Sustained attention, rapid processing, simultaneous monitoring. Exceptional performance potential and serious risk when unmanaged.", icon: Monitor },
  { title: "Shift patterns and fatigue management", description: "The interaction between shift fatigue and executive function creates cumulative risk standard frameworks do not account for.", icon: Moon },
  { title: "Customer-facing social demand", description: "Station staff and train managers carry significant social demand rarely factored into workload design.", icon: Users },
  { title: "Safety-critical assessment and disclosure", description: "Disclosure carries perceived fitness-for-role risk, suppressing support access.", icon: ShieldAlert },
  { title: "Non-technical skills assessments", description: "Competency frameworks including communication and teamwork can disadvantage excellent operational staff.", icon: Train },
];

const IndustryRail = () => (
  <>
    <SEOHead title="Neurodiversity in Rail & Transport" description="Neurodiversity training for rail and transport operators." path="/industries/rail-transport" />
    <JsonLd data={breadcrumbSchema([{ name: "Home", url: "https://www.neurodiversityglobal.com/" }, { name: "Industries", url: "https://www.neurodiversityglobal.com/industries" }, { name: "Rail & Transport", url: "https://www.neurodiversityglobal.com/industries/rail-transport" }])} />
    <JsonLd data={serviceSchema("Neurodiversity in Rail & Transport", "Neurodiversity training for rail and transport operations.", "https://www.neurodiversityglobal.com/industries/rail-transport")} />
    <JsonLd data={faqSchema(faqs)} />
    <Navbar /><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Industries", href: "/industries" }, { label: "Rail & Transport" }]} />
    <main>
      <section className="bg-primary text-primary-foreground py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center"><motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7 }}><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-4">Neurodiversity in rail</p><h1 className="font-display font-bold text-2xl md:text-3xl lg:text-4xl tracking-tight leading-[1.1]">Where safety-critical systems meet human cognitive variation</h1><p className="mt-5 text-sm md:text-base leading-relaxed opacity-80 max-w-[58ch]">Rail and transport depend on consistent performance in high-consequence environments. The question is whether your systems support cognitive diversity.</p></motion.div><motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.15 }} className="relative"><div className="rounded-2xl overflow-hidden shadow-xl"><img src={ndRailImg} alt="Rail control room" className="w-full h-[340px] lg:h-[400px] object-cover" loading="lazy" /></div><div className="absolute -bottom-6 -right-4 lg:-right-8 rounded-xl bg-card border border-border shadow-lg p-5 max-w-[200px]"><p className="font-display font-bold text-2xl text-accent">15+</p><p className="text-xs text-muted-foreground mt-1 leading-snug">Rail organisations supported</p></div></motion.div></div></div></section>
      <section className="bg-warm-stone py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">Key issues in 2026</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-foreground mb-10">Pressure points rail cannot ignore</h2><KeyIssuesGrid issues={keyIssues} /></div></section>
      <section className="bg-primary py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-primary-foreground mb-8">What is breaking right now</h2><WhatIsBreaking items={["Experienced drivers and operational staff exiting due to unsupported cognitive load", "Non-technical skills assessments creating disproportionate disadvantage", "Absence linked to sensory overload and shift fatigue going unrecognised", "Reasonable adjustments applied inconsistently across depots"]} /></div></section>
      <PullQuote quote="Safety culture that suppresses disclosure is not safe. It is hiding risk." accentIndex={1} />
      <section className="bg-warm-stone py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">The positives</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-foreground mb-10">Why rail should lead</h2><PositivesBlock items={[{ title: "Attention to detail is an operational asset", description: "Exceptional procedural accuracy directly valuable in safety-critical operations." }, { title: "Pattern recognition supports anomaly detection", description: "Identifying system anomalies and deviations has direct operational value." }, { title: "Strong regulatory framework provides a foundation", description: "Neuroinclusion maps directly onto existing compliance structures." }, { title: "Diverse cognitive teams make better safety decisions", description: "Cognitive diversity improves risk identification and reduces systematic error." }]} opportunity="Move from safety culture that suppresses disclosure to one that recognises cognitive diversity as operational strength." /></div></section>
      <section className="bg-primary py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">Your starting point</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-primary-foreground mb-10">Workshops built for rail</h2><RelevantWorkshops workshopIds={["awareness", "champions", "line-manager", "mental-health", "disclosure", "hr-training", "exec-briefing"]} title="Rail-recommended sessions" description="All adapted to safety-critical, shift-based environments." /></div></section>
      <section className="bg-warm-stone py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">Outcomes</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-foreground mb-10">What rail clients see</h2><OutcomeBlock title="Rail outcomes" outcomes={[{ metric: "30%", label: "more productive teams that include neurodivergent professionals." }, { label: "Improved disclosure rates across operational and engineering roles." }, { label: "More consistent adjustments across depots and control centres." }, { label: "Reduced sickness absence linked to unmanaged cognitive load." }, { label: "Stronger Equality Act compliance in safety-critical assessment." }]} /></div></section>
      <section className="bg-primary py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">Experience</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-primary-foreground mb-10">Our work in rail</h2><div className="grid md:grid-cols-2 gap-6"><TestimonialBlock quote="The training connected directly to our operational reality. Not generic. Not theoretical." author="Head of Safety" org="Rail Operator" /><div className="rounded-2xl border border-primary-foreground/10 bg-primary-foreground/[0.06] p-6 flex flex-col justify-center"><h3 className="font-display font-bold text-sm text-primary-foreground mb-4">Delivery experience</h3><div className="grid grid-cols-2 gap-5">{[{ value: "15+", label: "Rail organisations" }, { value: "1,200+", label: "Operational staff trained" }, { value: "15+", label: "Years in sector" }, { value: "UK-wide", label: "Including depots" }].map((s) => (<div key={s.label}><p className="font-display font-extrabold text-xl text-accent">{s.value}</p><p className="text-xs text-primary-foreground/60 mt-0.5">{s.label}</p></div>))}</div></div></div><div className="mt-8"><AccessibilityNote text="All materials designed for cognitive accessibility." /></div></div></section>
      <section className="bg-warm-stone py-20 lg:py-28"><div className="mx-auto max-w-wide px-6 lg:px-10"><p className="font-display font-bold text-sm uppercase tracking-[0.15em] text-accent mb-3">FAQs</p><h2 className="font-display font-bold text-xl md:text-2xl leading-tight text-foreground mb-10">Common questions</h2><div className="grid gap-4 max-w-2xl">{faqs.map((faq, i) => (<motion.div key={i} custom={i} initial="hidden" whileInView="visible" viewport={{ once: true }} variants={fadeUp} className="rounded-2xl border border-border bg-card p-6 shadow-sm overflow-hidden"><div className="h-1 -mx-6 -mt-6 mb-5" style={{ backgroundColor: NEURO_COLOURS[i % NEURO_COLOURS.length] }} /><h3 className="font-display font-bold text-sm text-card-foreground mb-2">{faq.question}</h3><p className="text-sm text-muted-foreground leading-relaxed">{faq.answer}</p></motion.div>))}</div></div></section>
      <PageCTA title="Ready to make neurodiversity work in rail?" description="Book a discovery call." />
    </main><Footer />
  </>
);

export default IndustryRail;